pooranjoyb/popShop

src/pages/Cart/Cart.tsx

Fixed the spinner in input
Fix: used div and state variables

Fixed the UI Issue

---

package-lock.json
package.json
src/pages/Auth/Auth.tsx
src/utils/schema.ts

- added zod library for form validation
- form-field error message addtion with appropriate style
Sample Image:

zod validation integration

---

package-lock.json
package.json
src/components/Footer.tsx
src/components/Navbar.tsx

issue fixed #22 
all icons changed with react-icons including cart icon also

raect-icons added

---

package-lock.json
package.json
src/App.tsx
src/components/Button.tsx
src/pages/Shop/ProductDetail.tsx
src/pages/Shop/Shop.tsx
src/utils/client.ts

Used React-Toastify and added Toast Notification on 'Add to Cart' Button. 
When the user now clicks on the 'Add to Cart' button, a notification toast will appear as shown in below video.
https://github.com/pooranjoyb/popShop/assets/132436131/2ebb2a3a-f0d7-4446-8ce3-4ed00c2dc991

[FIX] Added Toast Notification on 'Add to Cart' Button

---

src/pages/Home/Home.tsx

This PR fixes the issue #21 , kindly review it and merge.
Just a <Link> component was implement to link "view more" button to "/home/shop"
https://github.com/pooranjoyb/popShop/assets/75112434/27dd0c01-06a6-4fab-b552-e11464c3355b

view more button functionality

---

src/pages/Cart/Cart.tsx
src/pages/Cart/QuantityButton.tsx
src/pages/Shop/ProductDetail.tsx

Added a reusable component named QuantityButton.tsx under Cart component.

Fixed Quantity Button

---

package-lock.json
src/pages/Shop/Shop.tsx

I fixed the search feature on the products page now the users will be able to search for products using name of the product.

Fixed search feature

---

package-lock.json
src/pages/Shop/ProductDetail.tsx

**Issue #17  Fixed**
**Cloth size option functional added and  selected size updated in state**
**Screenshot**

Cloth size option functionality added

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/document.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
.github/ISSUE_TEMPLATE/refactor_code.yml
.github/pull_request_template.md

solve issue #49 
sir @pooranjoyb sorry for late and give me a good lavel for this beacause i make 5  issue template and one Pr template
Please can you give lavel3...otherwise minimum lavel 2...🙏

add_pr_template_with_issue_template

---

src/pages/Auth/ProtectedRoute.tsx

Changed Protected Route behavior to automatically redirected to login page.
Fixes #82 

feat-#82: Refining Protected Routes.

---

.github/workflows/autocomment-pr-merge.yml

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.
Fixes #120 

created autocomment-pr-merge.yml

---

src/components/Footer.tsx
src/components/Navbar.tsx
src/pages/Auth/Auth.tsx
src/pages/Error.tsx
src/pages/Home/Home.tsx

__Fixes #114__
- Fixes footer responsiveness for all screen widths.
- Fixes images not found in some routes
Used [Chrome DevTools](https://developer.chrome.com/docs/devtools/device-mode#responsive) to check for responsiveness
https://github.com/pooranjoyb/popShop/assets/70562711/6d9fc93c-cbeb-4971-b60c-e6f292244a2a

fix: make footer more responsive

---

src/pages/Auth/Auth.tsx
src/utils/schema.ts

Fixes #26
This pull request includes enhancements to the validation and error handling in the Auth component. The password rules have been strengthened to require at least one lowercase letter, one uppercase letter, one number, and one special character. Additionally, the error messages now appear as a list instead of a single string. These changes improve the user experience and make the authentication process more secure. Also error is displayed in list format

Enhance validation and error handling in Auth component

---

src/pages/Home/Home.tsx

Fixes #140 
Bug fix (non-breaking change which fixes an issue)
Opened the application in Chrome
Scrolled through the Home page and observed the transitions for each section
Confirmed that the sections animate into view as expected without any abrupt transitions
https://github.com/pooranjoyb/popShop/assets/127961738/dd7f2bcf-7e94-4305-a449-ad8bffac11ee
My code follows the style guidelines of this project
I have performed a self-review of my code
My …

fixing animation

---

src/pages/Auth/Auth.tsx

The form was not submitting when the user pressed the Enter key, which is a common expectation in web forms. This could lead to a poor user experience and confusion.
Motivation and Context
User Experience: Users typically expect pressing Enter to submit forms. Implementing this ensures intuitive interaction.
Form Consistency: Handling submission through the onSubmit event of the form element is standard practice, improving code maintainability and readability.
Fixes #149 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …

Feat: Enter Triggers Login

---

src/components/Navbar.tsx
src/pages/Shop/ProductDetail.tsx
src/utils/features/cart/cartSlice.ts
src/utils/features/store.ts

I have added the cart slice with its members and methods.
Fixes #94 

Cart slice

---

src/pages/Auth/Auth.tsx
src/utils/schema.ts

Saving User Data in db.

---

src/components/Button.tsx
src/pages/Auth/Auth.tsx
src/tailwind/output.css
tailwind.config.js

Updated Login and Signup frontend
Fixes # #156
- [✅ ] New feature (non-breaking change which adds functionality)
Just updated the current code with better features

[Feature] Enhance Authentication Screen #156

---

src/components/Navbar.tsx

Added the feature of closing dropdown on choosing an option from it.
It increases the user experience.
Fixes #166 
https://github.com/pooranjoyb/popShop/assets/124615886/f5e590d0-dbfd-408d-8f83-f508e4286c09

Close dropdown on choosing an option

---

src/browserRoutes/routes/Routes.tsx
src/components/Footer.tsx
src/pages/Contact/Contact.tsx
src/pages/T&C/TermsCond.tsx

Created Contact Us and Terms and Condition Page. Also did a little change on Footer to add links of these pages.
Fixes #165 and #174
Just created 2 pages - Contact Us and Terms and Condition Page

Added a contact page and terms & condition page

---

src/pages/Profile/EditProfileModal.tsx
src/pages/Profile/Profile.tsx

Users can update their data through Modal.
Kindly review and merge this PR under GSSOC'24.
Fixes #163 

Edit profile functionality added.

---

src/pages/Home/Home.tsx
src/pages/Profile/Profile.tsx
src/pages/Shop/Shop.tsx

The Styling and space were added on mentioned places.
Fixes #182 
Space removed and text visible on all devices
Content aligned at center
White space reduced.
Space added between header and component.
Space added.

Fix : Styling and Space

---

package-lock.json
package.json
src/pages/Contact/Contact.tsx
src/pages/Contact/FQA.tsx
src/tailwind/output.css

Added a FQAs section on contact page and implemented a working contact form on contact page.
Fixes #187
**Admin have to create an account on EmailJS service, and then create setup a Gmail service and add a template (with variables such as name, email, message). Now, copy EmailJS public key, service id and template id, and then add following fields to the `.env.local` file `VITE_EMAILJS_PUBLIC_KEY`, `VITE_EMAILJS_SERVICE_ID` and `VITE_EMAILJS_TEMPLATE_ID`.
Now simply fill contact form and send.**
[screen-recorder-wed-jun-05-2024-14-47-17.webm](https://github.com/pooranjoyb/popShop/assets/92575005/c10076b7-3e59-461e-bd5c-f7991eb4fcc1)

Implemented contact feature and added FQA section.

---

src/browserRoutes/routes/Routes.tsx
src/pages/Cart/Cart.tsx
src/pages/Checkout/Checkout.tsx
src/tailwind/output.css

Checkout page developed as static as per the given UI Design . Once we can easily setup dynamically once cart section is over.
**Fixes #191**

Checkout Page Developed

---

package-lock.json
src/pages/Shop/Shop.tsx

Fixes #117 
After making changes , i have tested by running npm run dev, and checked the output.
https://github.com/pooranjoyb/popShop/assets/121669832/8f98f354-8c35-4501-abb8-b9e6ab1d0a4a

Fix: Made shop header responsive.

---

package-lock.json
package.json
src/components/Navbar.tsx
src/pages/Cart/Cart.tsx

@pooranjoyb 
[Feat] : we can fetch cart from supabase #215
Fixes #215
- add some item in cart 
- try to go `/cart` route, all data come from supabase

update cart fetch data from supabase

---

src/pages/Cart/Cart.tsx

@pooranjoyb 
[Feature] Remove item from cart as well supabase #222
Fixes #222
- add some items in cart
- try to remove particular one
https://github.com/pooranjoyb/popShop/assets/114583978/56f8fee6-ddc1-42c1-bf73-d2969390b81d

remove item from cart success

---

src/pages/Cart/Cart.tsx
src/pages/Cart/QuantityButton.tsx
src/pages/Shop/ProductDetail.tsx

@pooranjoyb 
[BUG] update price when we increase quantity in cart #171
Fixes #171 (issue)
- go to cart and add some product
- try to change quantity of that
https://github.com/pooranjoyb/popShop/assets/114583978/1f5971e7-e902-4ee4-aa09-7adc70a79afb

Cart quantity

---

src/pages/Cart/Cart.tsx

@pooranjoyb 
[Feature] : Add toast message when removing items from cart #228
Fixes #228 (issue)

toast message while removing items from cart

---

package-lock.json
src/pages/Home/Home.tsx
src/pages/Shop/Shop.tsx

Implemented storage bucket on supabase to store product image, and also started fetching products form the database instead of using hardcoded data.
Fixes #232 
https://github.com/pooranjoyb/popShop/assets/92575005/a459a108-fca2-4a15-8995-b91f107170e0

Implemented storage bucket

---

src/pages/Profile/EditProfileModal.tsx

Fixed Bug: Profile not updating due to duplicate primary key
Fixes #238 
[screen-recorder-sat-jun-15-2024-09-10-29.webm](https://github.com/pooranjoyb/popShop/assets/92575005/68b99d5c-0f59-4eb6-8073-d93911719d86)

fixed bug: profile not updating 

---

src/browserRoutes/routes/Routes.tsx
src/components/Navbar.tsx
src/pages/Profile/MyOrders.tsx

- Added the `My Orders` page associated to an user's `Profile`
- Used static data for displaying orders
- Used `daisyUI` for maintaining the theme for the app
Fixes #234 
It has been tested on my local machine
https://github.com/pooranjoyb/popShop/assets/115717746/c11efcd7-d251-4f17-8716-b78b1cb5a3e4

Added My Orders Page

---

src/pages/Shop/Shop.tsx

@pooranjoyb 
[BUG] Fix the searchbar in Store #237
Fixes #237 (issue)
- go to products page and try to search products
https://github.com/pooranjoyb/popShop/assets/114583978/111545b5-49f4-473e-ae44-e8fe6e3e7dca

implementing search in products

---

src/components/Product.tsx
src/pages/Shop/Shop.tsx

[Feature] Apply filter in products #246
Fixes #246 (issue)
- changed $ to ₹ in product privce at home page and products page
- remove size option from filter
- apply filter based on price
- go to products page and apply any price filter …

Dynamic filter opetion on products

---

package-lock.json
src/components/Navbar.tsx

Now the cart price in navbar updates dynamically as we update the items in the cart.
Fixes #249 
Please describe the tests that you ran to verify your changes. 
Added the items to cart, changed their quantities and verified that the price gets updated correctly.
Provide instructions so we can reproduce. 
1. simply add some items in the cart
2. in the navbar click on the cart icon

Fixed the cart price issue in the navbar

---

src/pages/Checkout/Checkout.tsx

@pooranjoyb 
[Feature] Add Product Name while ordering product #256
Fixes #256 (issue)

add product detailes while ordering

---

src/pages/Profile/EditProfileModal.tsx

Resolved the issue that gender was not getting updated on edit profile. Added the feature to edit gender.
Fixes #281

Resolved Update-Profile-Details

---

src/pages/Cart/Cart.tsx

Added functionality to the `Apply` Button. 
Fixes #276
1. Open the cart.
2. Apply the coupon in the input field. 
3. DISCOUNT10 is the only coupon right now.
4. 10% is deducted from the total.
5. If any other coupon is applied, it shows invalid.

added functionality to coupons

---

src/pages/Shop/Shop.tsx

This PR Implements the filter functionality.
Fixes #305
[screen-recorder-mon-jul-08-2024-17-16-49.webm](https://github.com/pooranjoyb/popShop/assets/92575005/6212b14d-7a26-4262-b736-8e280db4178c)

Created Filter Feature

---

src/components/Navbar.tsx
src/pages/Cart/Cart.tsx
src/pages/Shop/ProductDetail.tsx

fixes issue #306 & #302

---

src/components/Navbar.tsx

Fixes #317 
- [x ] Bug fix (non-breaking change which fixes an issue)
I have checked in the localhost
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] My changes generate no new warnings
- [x ] I …

logo is added in the contact page

---

src/admin/AddProduct.tsx

in admin panel ,admin user able to add product detail in supabase using fill the form 
Fixes # (issue)
#303 
fill the form and clic on button then that data add in supabase product table 
and this is supabase image:

Product add in admin panel

---

src/components/Navbar.tsx
src/pages/Profile/Profile.tsx
src/utils/schema.ts

Fixes #297 
When you click on the profile image, option is given to select the image from your desktop to select any image. It is stored in the database and fetched.

Added profile image button

---

src/admin/AdminLayout/Sidebar.tsx
src/browserRoutes/routes/Routes.tsx
src/pages/AdminPage/Login.tsx
src/utils/features/Auth/authSlice.ts
src/utils/features/store.ts

@pooranjoyb 
[Feature] Add login before access admin panel #334
Fixes #334 (issue)
try to navigate `/admin` route
it take username and password for admin login
username : admin
password: Admin@123 

Protected Admin route added

---

src/browserRoutes/routes/Routes.tsx
src/pages/Auth/Auth.tsx
src/pages/Auth/ResetPassword.tsx

@pooranjoyb 
[Feature] Reset Password Feature #338
close #338
Fixes #338 (issue)
go to forgot passowd
enter your email
you recived one mail for reset password
enter your new password
try to login with new password
- due to limitation of request i just provide reset password ss
recived email:  …

reset password success

---

src/admin/AdminLayout/AdminLayout.tsx
src/admin/Transactions.tsx
src/components/Navbar.tsx
src/pages/Profile/Profile.tsx

@pooranjoyb 
- Added Profile Picture form DB if user have
- Add Beautiful Transaction Table 
Fixes #344 #345 (issue)
[Feature] If user is logged in with google we can display profile picture from it #344
[Feature] Display transaction from supabase #345

Admin and google dp

---

.dockerignore
Dockerfile
package.json

This feature was tested on docker , 
To reproduce , make sure the system it is tested have a docker installed . After that please make sure you have the .env.local file as it will copy all the files to docker . then run the commands that are added on package.json .
1. npm run docker-build
2. npm run docker-run
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added tests that prove my fix is …

Added Dockerfile to the Project for better testing in the system

---

src/pages/Orders/MyOrders.tsx

Fixes #337 
In this, when cancel order button is clicked, status changes from pending to cancelled in the database and the data is fetched again.
In this, same items are added to the cart and the item is navigated to the cart page.

Added buy again and cancel order features

---

package-lock.json
package.json
src/admin/Dashboard.tsx

in admin dashboard display realtime data 
Fixes # (issue)
#342 

Real time data in dashboard

---

src/components/Navbar.tsx
src/pages/Shop/Shop.tsx

@pooranjoyb 
[BUG] Filter not working in product #349
[BUG] Missing Burger Menu for routing in other pages #348
Fixes #349 #348 (issue)
https://github.com/user-attachments/assets/a4eba937-001f-4284-97bd-0405cbb9122f

Hamburger minor fixes

---

package-lock.json
package.json
react-tilt.d.ts
src/pages/Home/Home.tsx

@pooranjoyb 
[Feature] Want to add the tilt effect on the header image #323
Fixes #323 (issue)
https://github.com/user-attachments/assets/266ac04d-346e-421c-aeae-eb7ea400d9a2

add tilt effect

---

src/components/Footer.tsx
src/components/GoogleTranslateComponent.tsx

Fixes #352 
I checked the deployment on the local host

Issue #352 fixed. Added Google Language Translator. 

---

src/components/Product.tsx

@pooranjoyb 
[BUG] Aling Card #376
Fixes #376 (issue)

resolve height bug

---

CONTRIBUTING.md
src/components/Footer.tsx

Added spacing in footer section, previously image was all the way to down, which looked unordered
Fixes #385 

Sourabh782/enhanced footer UI
